// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpKi0m8d5MEwRVl7qLlydb3c2sjDtn5X8',
    appId: '1:336007296953:web:2778c52158b46cb6cda868',
    messagingSenderId: '336007296953',
    projectId: 'kos-management-12f4b',
    authDomain: 'kos-management-12f4b.firebaseapp.com',
    storageBucket: 'kos-management-12f4b.firebasestorage.app',
    measurementId: 'G-VWFK3Z5EG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8ipMD-cnHrpYtGkDbqWNNwjYqvUbNILs',
    appId: '1:336007296953:android:563b5fc577d384cbcda868',
    messagingSenderId: '336007296953',
    projectId: 'kos-management-12f4b',
    storageBucket: 'kos-management-12f4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZKgQL2uuxw2uaBn9u56vY0Sp-Ek4og1s',
    appId: '1:336007296953:ios:6451a19e19a0cd6ecda868',
    messagingSenderId: '336007296953',
    projectId: 'kos-management-12f4b',
    storageBucket: 'kos-management-12f4b.firebasestorage.app',
    iosBundleId: 'com.example.kosManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZKgQL2uuxw2uaBn9u56vY0Sp-Ek4og1s',
    appId: '1:336007296953:ios:6451a19e19a0cd6ecda868',
    messagingSenderId: '336007296953',
    projectId: 'kos-management-12f4b',
    storageBucket: 'kos-management-12f4b.firebasestorage.app',
    iosBundleId: 'com.example.kosManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpKi0m8d5MEwRVl7qLlydb3c2sjDtn5X8',
    appId: '1:336007296953:web:81ea903ce559272fcda868',
    messagingSenderId: '336007296953',
    projectId: 'kos-management-12f4b',
    authDomain: 'kos-management-12f4b.firebaseapp.com',
    storageBucket: 'kos-management-12f4b.firebasestorage.app',
    measurementId: 'G-GMJLGWJCVC',
  );
}
